### ISSUE TITLE
decompiling error pyc py 3.10

### ISSUE THREAD

**Issue by angelheart150** [serfend/pydumpck#13]
i have this message can you help me 
Traceback (most recent call last):
  File "/home/melsafty-linux/.local/bin/pydumpck", line 8, in <module>
    sys.exit(run())
  File "/home/melsafty-linux/.local/lib/python3.10/site-packages/pydumpck/pyinstaller_dump.py", line 105, in run
    return dmp.main(**vars(args))
  File "/home/melsafty-linux/.local/lib/python3.10/site-packages/pydumpck/py_common_dump/__init__.py", line 121, in main
    os.chdir(os.path.dirname(target_file))
FileNotFoundError: [Errno 2] No such file or directory: ''

![Screenshot from 2022-09-23 13-54-11](https://user-images.githubusercontent.com/67199651/191962684-25b581bb-90f6-4288-83fa-8dd68b389e8d.png)

**Comment by DevilXcry** [comment]
use ./ example:
 ./error.exe or
 ./yourfilename.pyc
