### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by 2Craft** [serfend/pydumpck#20]
OSError: [Errno 22] Invalid argument: 'output_4557329\\C:\\Users\\Administrator

getting this when decompiling a .pyc

**Comment by serfend** [comment]
additional `'` in path which lead to invalid-path.

**Comment by 2Craft** [comment]
And how can I fix it?

**Comment by serfend** [comment]
you can fix it by remove "additional ' in path which lead to invalid-path."

**Comment by serfend** [comment]
`'output_4557329\C:\Users\Administrator` is a invalid-path.
maybe you could use `C:\Users\Administrator\output_4557329` instead

**Comment by 2Craft** [comment]
I dont use any " or ' in the path:
C:\Users\EpicYT\Desktop\DEMO (1)\__pycache__>pydumpck C:\Users\EpicYT\Desktop\dump\BTC.pyc
2023-01-25 15:59:12,092 [+] pydumpck is a multi-threads tool for decompile exe,elf,pyz,pyc packed by python which is base on pycdc and uncompyle6.sometimes its py-file result not exactly right ,maybe could use uncompyle6.
--------------------
pydumpck initilizing with 1.15.14
349 +: pydumpck is a multi-threads tool for decompile exe,elf,pyz,pyc packed by python which is base on pycdc and uncompyle6.sometimes its py-file result not exactly right ,maybe could use uncompyle6.
--------------------
pydumpck initilizing with 1.15.14
2023-01-25 15:59:12,093 [*] plugins loaded with ['pycdc']
350 *: plugins loaded with ['pycdc']
2023-01-25 15:59:12,093 [*] target file input:C:\Users\EpicYT\Desktop\dump\BTC.pyc
to:output_9332464
350 *: target file input:C:\Users\EpicYT\Desktop\dump\BTC.pyc
to:output_9332464
2023-01-25 15:59:12,094 [*] start dump target file.
351 *: start dump target file.
Traceback (most recent call last):
  File "c:\users\epicyt\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\epicyt\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\EpicYT\AppData\Local\Programs\Python\Python38\Scripts\pydumpck.exe\__main__.py", line 7, in <module>
  File "c:\users\epicyt\appdata\local\programs\python\python38\lib\site-packages\pydumpck\pyinstaller_dump.py", line 118, in run
    return dmp.main(**vars(args))
  File "c:\users\epicyt\appdata\local\programs\python\python38\lib\site-packages\pydumpck\py_common_dump\__init__.py", line 157, in main
    self.result = self.action_dispatch[dispatch_to](target_file)
  File "c:\users\epicyt\appdata\local\programs\python\python38\lib\site-packages\pydumpck\py_common_dump\__init__.py", line 76, in handle_pyc_file
    shutil.copy(target_file, new_file)
  File "c:\users\epicyt\appdata\local\programs\python\python38\lib\shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "c:\users\epicyt\appdata\local\programs\python\python38\lib\shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
OSError: [Errno 22] Invalid argument: 'output_9332464\\C:\\Users\\EpicYT\\Desktop\\dump\\BTC.pyc'
it uses itself

**Comment by serfend** [comment]
fixed in [1.15.16](https://github.com/serfend/pydumpck/releases/tag/1.15.16)
thanks!

**Comment by 2Craft** [comment]
Thx!
