### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: ''

### ISSUE THREAD

**Issue by technicalanees** [serfend/pydumpck#22]
pydumpck h64.pyc --output ./output
2023-02-17 05:19:13,720 [+] pydumpck is a multi-threads tool for decompile exe,elf,pyz,pyc packed by python which is base on pycdc and uncompyle6.sometimes its py-file result not exactly right ,maybe could use uncompyle6.                                                                   
--------------------                                                                                                                            
pydumpck initilizing with 1.15.16                                                                                                               
164 +: pydumpck is a multi-threads tool for decompile exe,elf,pyz,pyc packed by python which is base on pycdc and uncompyle6.sometimes its py-file result not exactly right ,maybe could use uncompyle6.
--------------------
pydumpck initilizing with 1.15.16
2023-02-17 05:19:13,721 [*] plugins loaded with ['pycdc']
165 *: plugins loaded with ['pycdc']
2023-02-17 05:19:13,722 [*] target file input:h64.pyc
to:./output                                                                                                                                     
165 *: target file input:h64.pyc
to:./output
2023-02-17 05:19:13,722 [*] start dump target file.
166 *: start dump target file.
Traceback (most recent call last):
  File "/home/kali/Desktop/clone/hpro/venv/bin/pydumpck", line 8, in <module>
    sys.exit(run())
  File "/home/kali/Desktop/clone/hpro/venv/lib/python3.10/site-packages/pydumpck/pyinstaller_dump.py", line 118, in run
    return dmp.main(**vars(args))
  File "/home/kali/Desktop/clone/hpro/venv/lib/python3.10/site-packages/pydumpck/py_common_dump/__init__.py", line 157, in main
    os.chdir(os.path.dirname(target_file))
FileNotFoundError: [Errno 2] No such file or directory: ''

**Comment by saponciou** [comment]
same error with me

**Comment by listmen001** [comment]
so what's the solution?
the same error appeared.
