### ISSUE TITLE
ImportError: cannot import name 'get_archive'

### ISSUE THREAD

**Issue by PabloEscobaro24** [serfend/pydumpck#27]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Руслан\AppData\Local\Programs\Python\Python311\Scripts\pydumpck.exe\__main__.py", line 4, in <module>
  File "C:\Users\Руслан\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydumpck\__init__.py", line 22, in <module>
    from pydumpck.pyinstaller_dump import run
  File "C:\Users\Руслан\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydumpck\pyinstaller_dump.py", line 4, in <module>
    from pydumpck.py_common_dump import CommonDump
  File "C:\Users\Руслан\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydumpck\py_common_dump\__init__.py", line 7, in <module>
    from ..py_package import PackageStruct, PackageDescription
  File "C:\Users\Руслан\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydumpck\py_package\__init__.py", line 1, in <module>
    from .package_description import PackageDescription
  File "C:\Users\Руслан\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydumpck\py_package\package_description\__init__.py", line 6, in <module>
    from PyInstaller.utils.cliutils.archive_viewer import get_archive, get_data, get_content, get_archive_content
ImportError: cannot import name 'get_archive' from 'PyInstaller.utils.cliutils.archive_viewer' (C:\Users\Руслан\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\utils\cliutils\archive_viewer.py)

**Comment by roomyoni** [comment]
same issue

**Comment by NekoMoYi** [comment]
same issue
Package                   Version
------------------------- --------
altgraph                  0.17.3
click                     8.1.3
colorama                  0.4.6
colorlog                  6.7.0
et-xmlfile                1.1.0
openpyxl                  3.1.2
pefile                    2023.2.7
pip                       23.0.1
pycryptodome              3.17
pydumpck                  1.15.19
pyinstaller               5.10.1
pyinstaller-hooks-contrib 2023.2
pywin32-ctypes            0.2.0
setuptools                66.0.0
sgtpyutils                1.15.20
six                       1.16.0
spark-parser              1.8.9
tinyaes                   1.0.4
uncompyle6                3.9.0
wheel                     0.38.4
xdis                      6.0.5

**Comment by tabs** [comment]
why?

**Comment by SalemShotts** [comment]
I have luckily found a fix for this lol
Just reinstall pyinstaller under 5.9.0 as 5.10 and above does not seem to work.

However I have been getting another error: 

raise RuntimeError("%s is not a valid %s archive file" % (self.path, self.__class__.__name__))
RuntimeError: foo.exe is not a valid CArchiveReader archive file

**Comment by SonarServices** [comment]
Thankyou SalemShotts, this solved the issue for me.

**Comment by serfend** [comment]
updated [1.15.20](https://github.com/serfend/pydumpck/releases/tag/1.15.20)

**Comment by gumbobrot** [comment]
still getting that issue

**Comment by powellnorma** [comment]
same

```python3
Traceback (most recent call last):
  File "/venv3.11/bin/pydumpck", line 5, in <module>
    from pydumpck import run
  File "/venv3.11/lib64/python3.11/site-packages/pydumpck/__init__.py", line 22, in <module>
    from pydumpck.pyinstaller_dump import run
  File "/venv3.11/lib64/python3.11/site-packages/pydumpck/pyinstaller_dump.py", line 4, in <module>
    from pydumpck.py_common_dump import CommonDump
  File "/venv3.11/lib64/python3.11/site-packages/pydumpck/py_common_dump/__init__.py", line 7, in <module>
    from ..py_package import PackageStruct, PackageDescription
  File "/venv3.11/lib64/python3.11/site-packages/pydumpck/py_package/__init__.py", line 1, in <module>
    from .package_description import PackageDescription
  File "/venv3.11/lib64/python3.11/site-packages/pydumpck/py_package/package_description/__init__.py", line 6, in <module>
    from PyInstaller.utils.cliutils.archive_viewer import get_archive, get_data, get_content, get_archive_content
ImportError: cannot import name 'get_archive' from 'PyInstaller.utils.cliutils.archive_viewer' (/venv3.11/lib64/python3.11/site-packages/PyInstaller/utils/cliutils/archive_viewer.py)
```

**Comment by Divertisment** [comment]
same @serfend
`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python312\Scripts\pydumpck.exe\__main__.py", line 4, in <module>
  File "C:\Python312\Lib\site-packages\pydumpck\__init__.py", line 22, in <module>
    from pydumpck.pyinstaller_dump import run
  File "C:\Python312\Lib\site-packages\pydumpck\pyinstaller_dump.py", line 4, in <module>
    from pydumpck.py_common_dump import CommonDump
  File "C:\Python312\Lib\site-packages\pydumpck\py_common_dump\__init__.py", line 7, in <module>
    from ..py_package import PackageStruct, PackageDescription
  File "C:\Python312\Lib\site-packages\pydumpck\py_package\__init__.py", line 1, in <module>
    from .package_description import PackageDescription
  File "C:\Python312\Lib\site-packages\pydumpck\py_package\package_description\__init__.py", line 6, in <module>
    from PyInstaller.utils.cliutils.archive_viewer import get_archive, get_data, get_content, get_archive_content
ImportError: cannot import name 'get_archive' from 'PyInstaller.utils.cliutils.archive_viewer' (C:\Python312\Lib\site-packages\PyInstaller\utils\cliutils\archive_viewer.py)`

**Comment by LimerBoy** [comment]
pip install pyinstaller==5.9.0

**Comment by zoskiinepaster** [comment]
I writed pip install pyinstaller==5.9.0, and

ERROR: Ignored the following versions that require a different python version: 4.10 Requires-Python <3.11,>=3.6; 4.6 Requires-Python <3.11,>=3.6; 4.7 Requires-Python <3.11,>=3.6; 4.8 Requires-Python <3.11,>=3.6; 4.9 Requires-Python <3.11,>=3.6; 5.0 Requires-Python <3.11,>=3.7; 5.0.1 Requires-Python <3.11,>=3.7; 5.1 Requires-Python <3.11,>=3.7; 5.10.0 Requires-Python <3.12,>=3.7; 5.10.1 Requires-Python <3.12,>=3.7; 5.11.0 Requires-Python <3.12,>=3.7; 5.12.0 Requires-Python <3.12,>=3.7; 5.2 Requires-Python <3.11,>=3.7; 5.3 Requires-Python <3.11,>=3.7; 5.4 Requires-Python <3.11,>=3.7; 5.4.1 Requires-Python <3.11,>=3.7; 5.5 Requires-Python <3.12,>=3.7; 5.6 Requires-Python <3.12,>=3.7; 5.6.1 Requires-Python <3.12,>=3.7; 5.6.2 Requires-Python <3.12,>=3.7; 5.7.0 Requires-Python <3.12,>=3.7; 5.8.0 Requires-Python <3.12,>=3.7; 5.9.0 Requires-Python <3.12,>=3.7
ERROR: Could not find a version that satisfies the requirement pyinstaller==5.9.0 (from versions: 2.0, 2.1, 3.0, 3.1, 3.1.1, 3.2, 3.2.1, 3.3, 3.3.1, 3.4, 3.5, 3.6, 4.0, 4.1, 4.2, 4.3, 4.4, 4.5, 4.5.1, 5.13.0, 5.13.1, 5.13.2, 6.0.0, 6.1.0, 6.2.0, 6.3.0, 6.4.0)
ERROR: No matching distribution found for pyinstaller==5.9.0

**Comment by Divertisment** [comment]
> pip install pyinstaller==5.9.0

![image](https://github.com/serfend/pydumpck/assets/5182065/edb21d1b-59b8-446f-8c9b-702f7f7e695c)
