### ISSUE TITLE
PyInstaller.loader.pyimod01_archive.ArchiveReadError: Could not find COOKIE magic pattern!

### ISSUE THREAD

**Issue by SalemShotts** [serfend/pydumpck#28]
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\surru\OneDrive\Desktop\New folder\pydumpck.exe\__main__.py", line 7, in <module>
  File "C:\Users\surru\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pydumpck\pyinstaller_dump.py", line 118, in run
    return dmp.main(**vars(args))
  File "C:\Users\surru\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pydumpck\py_common_dump\__init__.py", line 203, in main
    self.result = self.action_dispatch[dispatch_to](target_file)
  File "C:\Users\surru\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pydumpck\py_common_dump\__init__.py", line 121, in handle_arch_file
    arch = get_archive(filename=target_file)
  File "C:\Users\surru\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pydumpck\py_common_dump\__init__.py", line 25, in get_archive
    arch = viewer._open_toplevel_archive(filename)
  File "C:\Users\surru\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\PyInstaller\utils\cliutils\archive_viewer.py", line 126, in _open_toplevel_archive
    return CArchiveReader(filename)
  File "C:\Users\surru\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\PyInstaller\archive\readers.py", line 90, in __init__
    raise ArchiveReadError("Could not find COOKIE magic pattern!")
PyInstaller.loader.pyimod01_archive.ArchiveReadError: Could not find COOKIE magic pattern!
-------------------------------
This is a new error im getting while testing out the new version, any fixes?

**Comment by serfend** [comment]
need any attachment for reoccurrence
