### ISSUE TITLE
error

### ISSUE THREAD

**Issue by TheCloudLad** [serfend/pydumpck#36]
─$ pydumpck
Traceback (most recent call last):
  File "/home/kali/.local/bin/pydumpck", line 5, in <module>
    from pydumpck import run
  File "/home/kali/.local/lib/python3.11/site-packages/pydumpck/__init__.py", line 22, in <module>
    from pydumpck.pyinstaller_dump import run
  File "/home/kali/.local/lib/python3.11/site-packages/pydumpck/pyinstaller_dump.py", line 4, in <module>
    from pydumpck.py_common_dump import CommonDump
  File "/home/kali/.local/lib/python3.11/site-packages/pydumpck/py_common_dump/__init__.py", line 7, in <module>
    from ..py_package import PackageStruct, PackageDescription
  File "/home/kali/.local/lib/python3.11/site-packages/pydumpck/py_package/__init__.py", line 1, in <module>
    from .package_description import PackageDescription
  File "/home/kali/.local/lib/python3.11/site-packages/pydumpck/py_package/package_description/__init__.py", line 6, in <module>
    from PyInstaller.utils.cliutils.archive_viewer import get_archive, get_data, get_content, get_archive_content
ImportError: cannot import name 'get_archive' from 'PyInstaller.utils.cliutils.archive_viewer' (/home/kali/.local/lib/python3.11/site-packages/PyInstaller/utils/cliutils/archive_viewer.py)

**Comment by bloban** [comment]
Did you solve it?

**Comment by serfend** [comment]
same as #27

**Comment by TheCloudLad** [comment]
no i don't work with this tool , I wan't to use it for some python malware that someone try to give it to me , I don't open it but I wan't to see the code if you have any tool for this thing replay on this
