### ISSUE TITLE
error during decompiling

### ISSUE THREAD

**Issue by LocalSmail223** [serfend/pydumpck#39]
Not sure what is wrong as it doesnt really print the error. 
I used an old tool called pyinstxtractor to decompile the pyinstaller 2.1+ exe. (It wont decompile the exe if it doesnt know the version of pyinstaller.)

```
C:\Users\userhere>pydumpck "C:\Users\userhere\main (1).exe_extracted\main.pyc" -o output -d -p pycdc uncompyle6
2023-08-11 03:21:50,269 [+] pydumpck is a multi-threads tool for decompile exe,elf,pyz,pyc packed by python which is base on pycdc and uncompyle6.sometimes its py-file result not exactly right ,maybe could use uncompyle6.
--------------------
pydumpck initilizing with 1.16.2
378 +: pydumpck is a multi-threads tool for decompile exe,elf,pyz,pyc packed by python which is base on pycdc and uncompyle6.sometimes its py-file result not exactly right ,maybe could use uncompyle6.
--------------------
pydumpck initilizing with 1.16.2
2023-08-11 03:21:50,274 [*] plugins loaded with ['pycdc', 'uncompyle6']
384 *: plugins loaded with ['pycdc', 'uncompyle6']
2023-08-11 03:21:50,275 [-] attention! when use uncompyle6 , you should use --decompile_file specified which file to decompile for faster task.
384 -: attention! when use uncompyle6 , you should use --decompile_file specified which file to decompile for faster task.
2023-08-11 03:21:53,284 [*] target file input:C:\Users\userhere\main (1).exe_extracted\main.pyc
to:output
3393 *: target file input:C:\Users\userhere\main (1).exe_extracted\main.pyc
to:output
2023-08-11 03:21:53,287 [*] start dump target file. type:pyc
3396 *: start dump target file. type:pyc
Unknown type 0
Unknown type 23 ↨
Unknown type 0
Unknown type 100 d
Unknown type 0
Unknown type 100 d
Unknown type 1 ☺
Unknown type 0
Unknown type 23 ↨
Unknown type 0
Unknown type 100 d
Unknown type 0
Unknown type 100 d
Unknown type 1 ☺
Unknown type 0
Unknown type 23 ↨
Unknown type 0
Unknown type 100 d
Unknown type 0
Unknown type 100 d
Unknown type 1 ☺
Traceback (most recent call last):
  File "c:\users\userhere\appdata\local\programs\python\python39\lib\site-packages\pydumpck\py_package\package_struct\__init__.py", line 36, in decompile_pyc
    code, err = pyc_checker.dump_pyc(file, file, t)
  File "c:\users\userhere\appdata\local\programs\python\python39\lib\site-packages\pydumpck\pyc_checker\__init__.py", line 125, in dump_pyc
    return dump(data, target_file, structed_pyc_file, timeout, use_attach_header)
  File "c:\users\userhere\appdata\local\programs\python\python39\lib\site-packages\pydumpck\pyc_checker\__init__.py", line 97, in dump
    same, data = default_pyc.attach_pyc_struct(data, structed_pyc_file)
  File "c:\users\userhere\appdata\local\programs\python\python39\lib\site-packages\pydumpck\pyc_checker\pyc\__init__.py", line 64, in attach_pyc_struct
    same, data = self.attach_header(data)
  File "c:\users\userhere\appdata\local\programs\python\python39\lib\site-packages\pydumpck\pyc_checker\pyc\__init__.py", line 57, in attach_header
    raise Exception('[!] invalid pyc-struct data')
Exception: [!] invalid pyc-struct data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\userhere\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\carpal\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\userhere\AppData\Local\Programs\Python\Python39\Scripts\pydumpck.exe\__main__.py", line 7, in <module>
  File "c:\users\userhere\appdata\local\programs\python\python39\lib\site-packages\pydumpck\pyinstaller_dump.py", line 118, in run
    return dmp.main(**vars(args))
  File "c:\users\userhere\appdata\local\programs\python\python39\lib\site-packages\pydumpck\py_common_dump\__init__.py", line 203, in main
    self.result = self.action_dispatch[dispatch_to](target_file)
  File "c:\users\userhere\appdata\local\programs\python\python39\lib\site-packages\pydumpck\py_common_dump\__init__.py", line 116, in handle_pyc_file
    PackageStruct.decompile_pyc(new_file)
  File "c:\users\userhere\appdata\local\programs\python\python39\lib\site-packages\pydumpck\py_package\package_struct\__init__.py", line 45, in decompile_pyc
    f'Exception on decompile bytecode file:{file},with error:{err}')
UnboundLocalError: local variable 'err' referenced before assignment
```

**Comment by serfend** [comment]
fixed in [1.16.3](https://github.com/serfend/pydumpck/releases/tag/1.16.3)
