### ISSUE TITLE
ImportError: cannot import name 'get_archive' from 'PyInstaller.utils.cliutils.archive_viewer'

### ISSUE THREAD

**Issue by jakkapong1129** [serfend/pydumpck#52]
![image](https://github.com/serfend/pydumpck/assets/60910772/e4094e0d-fa1d-4781-ad93-d94830d72698)

**Comment by serfend** [comment]
try run
```shell
pip install pydumpck --upgrade
```

**Comment by TheRealPotatoe** [comment]
still getting the same after running that command 
![image](https://github.com/serfend/pydumpck/assets/99142109/78d3bc01-9b45-4b9b-b419-e7c7b9702626)

**Comment by serfend** [comment]
the latest version of `pydumpck` is rewrite `archive_view` itself.
from your screenshot , i guess that your `pydumpck` maybe outdated

**Comment by Divertisment** [comment]
pip install pydumpck --upgrade --Done but still....
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python312\Scripts\pydumpck.exe\__main__.py", line 4, in <module>
  File "C:\Python312\Lib\site-packages\pydumpck\__init__.py", line 22, in <module>
    from pydumpck.pyinstaller_dump import run
  File "C:\Python312\Lib\site-packages\pydumpck\pyinstaller_dump.py", line 4, in <module>
    from pydumpck.py_common_dump import CommonDump
  File "C:\Python312\Lib\site-packages\pydumpck\py_common_dump\__init__.py", line 7, in <module>
    from ..py_package import PackageStruct, PackageDescription
  File "C:\Python312\Lib\site-packages\pydumpck\py_package\__init__.py", line 1, in <module>
    from .package_description import PackageDescription
  File "C:\Python312\Lib\site-packages\pydumpck\py_package\package_description\__init__.py", line 6, in <module>
    from PyInstaller.utils.cliutils.archive_viewer import get_archive, get_data, get_content, get_archive_content
ImportError: cannot import name 'get_archive' from 'PyInstaller.utils.cliutils.archive_viewer' (C:\Python312\Lib\site-packages\PyInstaller\utils\cliutils\archive_viewer.py)
```
