### ISSUE TITLE
can't run pydumpck: ModuleNotFoundError: No module named 'tinyaes'

### ISSUE THREAD

**Issue by greenozon** [serfend/pydumpck#54]
here are the steps done:

```
c:\Prg\M>pip install pydumpck
Collecting pydumpck
  Downloading pydumpck-1.17.9-py3-none-any.whl.metadata (7.2 kB)
Collecting sgtpyutils>=1.16.0 (from pydumpck)
  Downloading sgtpyutils-1.17.13-py3-none-any.whl.metadata (4.9 kB)
Collecting pyinstaller>=5.10.1 (from pydumpck)
  Downloading pyinstaller-6.3.0-py3-none-win_amd64.whl.metadata (8.3 kB)
Collecting tinyaes (from pydumpck)
  Downloading tinyaes-1.1.0.tar.gz (71 kB)
     ---------------------------------------- 71.7/71.7 kB 788.4 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting uncompyle6>=3.9.0 (from pydumpck)
  Downloading uncompyle6-3.9.0-py38-none-any.whl (381 kB)
     ---------------------------------------- 381.1/381.1 kB 4.8 MB/s eta 0:00:00
Collecting xdis>=6.0.5 (from pydumpck)
  Downloading xdis-6.0.5-py310-none-any.whl (144 kB)
     ---------------------------------------- 144.9/144.9 kB 8.4 MB/s eta 0:00:00
Requirement already satisfied: setuptools>=42.0.0 in c:\python312\lib\site-packages (from pyinstaller>=5.10.1->pydumpck) (68.2.2)
Collecting altgraph (from pyinstaller>=5.10.1->pydumpck)
  Using cached altgraph-0.17.4-py2.py3-none-any.whl.metadata (7.3 kB)
Collecting pyinstaller-hooks-contrib>=2021.4 (from pyinstaller>=5.10.1->pydumpck)
  Downloading pyinstaller_hooks_contrib-2023.11-py2.py3-none-any.whl.metadata (15 kB)
Collecting packaging>=22.0 (from pyinstaller>=5.10.1->pydumpck)
  Using cached packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
Collecting pefile>=2022.5.30 (from pyinstaller>=5.10.1->pydumpck)
  Using cached pefile-2023.2.7-py3-none-any.whl (71 kB)
Collecting pywin32-ctypes>=0.2.1 (from pyinstaller>=5.10.1->pydumpck)
  Using cached pywin32_ctypes-0.2.2-py3-none-any.whl.metadata (3.8 kB)
Collecting scidatetime>1.17.13 (from sgtpyutils>=1.16.0->pydumpck)
  Downloading scidatetime-1.17.15-py3-none-any.whl.metadata (4.5 kB)
Collecting pycryptodome (from sgtpyutils>=1.16.0->pydumpck)
  Downloading pycryptodome-3.19.0-cp35-abi3-win_amd64.whl.metadata (3.4 kB)
Collecting colorlog (from sgtpyutils>=1.16.0->pydumpck)
  Downloading colorlog-6.8.0-py3-none-any.whl.metadata (10 kB)
Collecting openpyxl>=3.1.0 (from sgtpyutils>=1.16.0->pydumpck)
  Downloading openpyxl-3.1.2-py2.py3-none-any.whl (249 kB)
     ---------------------------------------- 250.0/250.0 kB 15.0 MB/s eta 0:00:00
Collecting argparse (from sgtpyutils>=1.16.0->pydumpck)
  Downloading argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Collecting httpx[http2] (from sgtpyutils>=1.16.0->pydumpck)
  Downloading httpx-0.26.0-py3-none-any.whl.metadata (7.6 kB)
Collecting redis (from sgtpyutils>=1.16.0->pydumpck)
  Downloading redis-5.0.1-py3-none-any.whl.metadata (8.9 kB)
Collecting fake-useragent (from sgtpyutils>=1.16.0->pydumpck)
  Downloading fake_useragent-1.4.0-py3-none-any.whl.metadata (13 kB)
Collecting six (from sgtpyutils>=1.16.0->pydumpck)
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting pathlib2 (from sgtpyutils>=1.16.0->pydumpck)
  Downloading pathlib2-2.3.7.post1-py2.py3-none-any.whl (18 kB)
Collecting spark-parser<1.9.0,>=1.8.9 (from uncompyle6>=3.9.0->pydumpck)
  Downloading spark_parser-1.8.9-py3-none-any.whl (17 kB)
Collecting click (from xdis>=6.0.5->pydumpck)
  Downloading click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
INFO: pip is looking at multiple versions of xdis to determine which version is compatible with other requirements. This could take a while.
Collecting sgtpyutils>=1.16.0 (from pydumpck)
  Downloading sgtpyutils-1.17.9-py3-none-any.whl.metadata (1.4 kB)
  Downloading sgtpyutils-1.17.7-py3-none-any.whl.metadata (1.3 kB)
  Downloading sgtpyutils-1.17.5-py3-none-any.whl.metadata (1.3 kB)
  Downloading sgtpyutils-1.17.1-py3-none-any.whl.metadata (1.4 kB)
  Downloading sgtpyutils-1.17.0-py3-none-any.whl.metadata (1.4 kB)
  Downloading sgtpyutils-1.16.0-py3-none-any.whl.metadata (1.4 kB)
Collecting pyinstaller>=5.10.1 (from pydumpck)
  Using cached pyinstaller-6.2.0-py3-none-win_amd64.whl.metadata (8.3 kB)
INFO: pip is still looking at multiple versions of xdis to determine which version is compatible with other requirements. This could take a while.
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If yo
u want to abort this run, press Ctrl + C.
  Downloading pyinstaller-6.1.0-py3-none-win_amd64.whl.metadata (8.2 kB)
  Downloading pyinstaller-6.0.0-py3-none-win_amd64.whl.metadata (8.2 kB)
  Downloading pyinstaller-5.13.2-py3-none-win_amd64.whl.metadata (8.3 kB)
  Downloading pyinstaller-5.13.1-py3-none-win_amd64.whl.metadata (8.3 kB)
  Downloading pyinstaller-5.13.0-py3-none-win_amd64.whl.metadata (8.3 kB)
Collecting pydumpck
  Downloading pydumpck-1.16.3-py3-none-any.whl.metadata (7.2 kB)
  Downloading pydumpck-1.16.2-py3-none-any.whl.metadata (7.1 kB)
  Downloading pydumpck-1.16.0-py3-none-any.whl (682 kB)
     ---------------------------------------- 682.9/682.9 kB 10.8 MB/s eta 0:00:00
Collecting sgtpyutils>=1.15.22 (from pydumpck)
  Downloading sgtpyutils-1.15.27-py3-none-any.whl.metadata (1.4 kB)
  Downloading sgtpyutils-1.15.25-py3-none-any.whl.metadata (1.3 kB)
  Downloading sgtpyutils-1.15.24-py3-none-any.whl.metadata (1.3 kB)
  Downloading sgtpyutils-1.15.23-py3-none-any.whl.metadata (1.3 kB)
  Downloading sgtpyutils-1.15.22-py3-none-any.whl (31 kB)
Collecting pydumpck
  Downloading pydumpck-1.15.21-py3-none-any.whl (682 kB)
     ---------------------------------------- 682.9/682.9 kB 8.6 MB/s eta 0:00:00
Collecting xdis>=6.0.4 (from pydumpck)
  Downloading xdis-6.0.4-py310-none-any.whl (139 kB)
     ---------------------------------------- 139.1/139.1 kB ? eta 0:00:00
Collecting sgtpyutils>=1.15.14 (from pydumpck)
  Downloading sgtpyutils-1.15.20-py3-none-any.whl (31 kB)
  Downloading sgtpyutils-1.15.17-py3-none-any.whl (31 kB)
  Downloading sgtpyutils-1.15.15-py3-none-any.whl (31 kB)
  Downloading sgtpyutils-1.15.14-py3-none-any.whl (30 kB)
Collecting pydumpck
  Downloading pydumpck-1.15.20-py3-none-any.whl (561 kB)
     ---------------------------------------- 561.5/561.5 kB 8.9 MB/s eta 0:00:00
  Downloading pydumpck-1.15.19-py3-none-any.whl (560 kB)
     ---------------------------------------- 560.8/560.8 kB 8.9 MB/s eta 0:00:00
  Downloading pydumpck-1.15.16-py3-none-any.whl (1.4 MB)
     ---------------------------------------- 1.4/1.4 MB 9.6 MB/s eta 0:00:00
  Downloading pydumpck-1.15.14-py3-none-any.whl (1.4 MB)
     ---------------------------------------- 1.4/1.4 MB 9.6 MB/s eta 0:00:00
  Downloading pydumpck-1.15.11-py3-none-any.whl (1.4 MB)
     ---------------------------------------- 1.4/1.4 MB 7.9 MB/s eta 0:00:00
Collecting sgtpyutils>=1.15.10 (from pydumpck)
  Downloading sgtpyutils-1.15.10-py3-none-any.whl (30 kB)
Collecting pydumpck
  Downloading pydumpck-1.15.8-py3-none-any.whl (1.4 MB)
     ---------------------------------------- 1.4/1.4 MB 8.6 MB/s eta 0:00:00
  Downloading pydumpck-1.14.6-py3-none-any.whl (1.4 MB)
     ---------------------------------------- 1.4/1.4 MB 9.6 MB/s eta 0:00:00
  Downloading pydumpck-1.7.62-py3-none-any.whl (1.4 MB)
     ---------------------------------------- 1.4/1.4 MB 8.6 MB/s eta 0:00:00
  Downloading pydumpck-1.6.168-py3-none-any.whl (1.4 MB)
     ---------------------------------------- 1.4/1.4 MB 9.5 MB/s eta 0:00:00
  Downloading pydumpck-1.6.164-py3-none-any.whl (548 kB)
     ---------------------------------------- 548.6/548.6 kB 11.5 MB/s eta 0:00:00
  Downloading pydumpck-1.5.132-py3-none-any.whl (544 kB)
     ---------------------------------------- 544.1/544.1 kB 8.6 MB/s eta 0:00:00
  Downloading pydumpck-1.5.126-py3-none-any.whl (543 kB)
     ---------------------------------------- 543.1/543.1 kB 8.6 MB/s eta 0:00:00
  Downloading pydumpck-1.5.125-py3-none-any.whl (543 kB)
     ---------------------------------------- 543.1/543.1 kB 8.6 MB/s eta 0:00:00
  Downloading pydumpck-1.5.114-py3-none-any.whl (542 kB)
     ---------------------------------------- 542.8/542.8 kB 8.6 MB/s eta 0:00:00
  Downloading pydumpck-1.5.113-py3-none-any.whl (542 kB)
     ---------------------------------------- 542.8/542.8 kB 8.6 MB/s eta 0:00:00
Installing collected packages: pydumpck
Successfully installed pydumpck-1.5.113

[notice] A new release of pip is available: 23.3.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip

```

Now when I try to run the tool it shows this traceback:

```
c:\Prg\M>pydumpck
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python312\Scripts\pydumpck.exe\__main__.py", line 4, in <module>
  File "C:\Python312\Lib\site-packages\pydumpck\__init__.py", line 22, in <module>
    from pydumpck.pyinstaller_dump import run
  File "C:\Python312\Lib\site-packages\pydumpck\pyinstaller_dump.py", line 4, in <module>
    from pydumpck.py_common_dump import CommonDump
  File "C:\Python312\Lib\site-packages\pydumpck\py_common_dump\__init__.py", line 7, in <module>
    from ..py_package import PackageStruct, PackageDescription
  File "C:\Python312\Lib\site-packages\pydumpck\py_package\__init__.py", line 1, in <module>
    from .package_description import PackageDescription
  File "C:\Python312\Lib\site-packages\pydumpck\py_package\package_description\__init__.py", line 4, in <module>
    from ...pyc_checker import pyz_extract
  File "C:\Python312\Lib\site-packages\pydumpck\pyc_checker\pyz_extract.py", line 8, in <module>
    import tinyaes
ModuleNotFoundError: No module named 'tinyaes'
```

my python is:

c:\Prg\M>python -V
Python 3.12.0

**Comment by greenozon** [comment]
I see that official supported last version is python 3.11

![image](https://github.com/serfend/pydumpck/assets/765343/ed482297-c51d-45bd-957d-1c4e0aaf685d)

so the question about running tool on 3.12 is actual

**Comment by serfend** [comment]
`pydumpck-1.5.113` maybe is outdate , try use `pip install pydumpck --upgrade`
the latest is [1.17.10](https://github.com/serfend/pydumpck/releases/tag/1.17.10)

**Comment by alamerrouka** [comment]
pydumpck "/sdcard/Download/GAY_TEAM/enc_simple.cpython-311.so"           Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/pydumpck", line 5, in <module>
    from pydumpck import run
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pydumpck/__init__.py", line 22, in <module>
    from pydumpck.pyinstaller_dump import run
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pydumpck/pyinstaller_dump.py", line 4, in <module>
    from pydumpck.py_common_dump import CommonDump
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pydumpck/py_common_dump/__init__.py", line 7, in <module>
    from ..py_package import PackageStruct, PackageDescription
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pydumpck/py_package/__init__.py", line 1, in <module>
    from .package_description import PackageDescription
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pydumpck/py_package/package_description/__init__.py", line 6, in <module>
    from PyInstaller.utils.cliutils.archive_viewer import get_archive, get_data, get_content, get_archive_content
ImportError: cannot import name 'get_archive' from 'PyInstaller.utils.cliutils.archive_viewer' (/data/data/com.termux/files/usr/lib/python3.11/site-packages/PyInstaller/utils/cliutils/archive_viewer.py)

how can i solve this problem

**Comment by becauseimnoob** [comment]
> pydumpck "/sdcard/Download/GAY_TEAM/enc_simple.cpython-311.so" Traceback (most recent call last): File "/data/data/com.termux/files/usr/bin/pydumpck", line 5, in from pydumpck import run File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pydumpck/**init**.py", line 22, in from pydumpck.pyinstaller_dump import run File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pydumpck/pyinstaller_dump.py", line 4, in from pydumpck.py_common_dump import CommonDump File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pydumpck/py_common_dump/**init**.py", line 7, in from ..py_package import PackageStruct, PackageDescription File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pydumpck/py_package/**init**.py", line 1, in from .package_description import PackageDescription File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pydumpck/py_package/package_description/**init**.py", line 6, in from PyInstaller.utils.cliutils.archive_viewer import get_archive, get_data, get_content, get_archive_content ImportError: cannot import name 'get_archive' from 'PyInstaller.utils.cliutils.archive_viewer' (/data/data/com.termux/files/usr/lib/python3.11/site-packages/PyInstaller/utils/cliutils/archive_viewer.py)
> 
> how can i solve this problem

I have the same problem, did you solve it? @serfend

**Comment by serfend** [comment]
check if any error occurred in install package like folling.`Microsoft Visual C++ 14.0 or greater is required.` you should download and install it first.

```sh
Building wheels for collected packages: tinyaes
  Building wheel for tinyaes (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for tinyaes (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'tinyaes' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tinyaes
Failed to build tinyaes
ERROR: Could not build wheels for tinyaes, which is required to install pyproject.toml-based projects
```
