### ISSUE TITLE
decompile .pyc文件错误！ 

### ISSUE THREAD

**Issue by dmmhk** [serfend/pydumpck#9]
文件：[baidu_click.zip](https://github.com/serfend/pydumpck/files/8945077/baidu_click.zip)
已知文件版本：python 3.8；
测试uncompyle6是解不开的。
使用pydumpck的pycdc模式 大量“# WARNING: Decompyle incomplete”编译未完成，尴尬啊。
帮忙测试一下是否正常！
baidu_click是一个快排程序，主要刷百度搜索点击的，

**Comment by serfend** [comment]
```bash
$ baidu_click.pyc
RuntimeError: Bad magic number in .pyc file
```

**Comment by serfend** [comment]
```bash
$ baidu_click_structed.pyc
Traceback (most recent call last):
  File "baidu_click.py", line 296, in <module>
  File "baidu_click.py", line 14, in read_ini
  File "~\Python\Python310\lib\configparser.py", line 782, in get
    d = self._unify_values(section, vars)
  File "~\Python\Python310\lib\configparser.py", line 1153, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'baseConfig'
```

**Comment by dmmhk** [comment]
[百度PC前十模拟点击.zip](https://github.com/serfend/pydumpck/files/8966197/PC.zip)

完整文件不清楚是否有影响
